#include "./measures/average_sign.hpp"
#include "./measures/M_tau.hpp"
#include "./measures/M_iw.hpp"
#include "./measures/F_tau.hpp"
#include "./measures/M4_iw.hpp"
#include "./measures/M3_iw.hpp"
#include "./measures/M2_tau.hpp"
